spring.application.name=demo

logging.level.root=INFO
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.web=WARN
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.transaction.interceptor=TRACE
logging.file.name=logs/app.log
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg&n

# H2 in memory
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Enable H2 console
spring.h2.console.enabled=true

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security
spring.security.user.name=admin
spring.security.user.password=admin123
