spring.application.name=demo

spring.security.user.name=admin
spring.security.user.password=1234

logging.level.rool=INFO

logging.level.com.example.demo=DEBUG

logging.level.org.springframework.web=WARN

logging.file.name=logs/app.log

logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36} - %msg&n